Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ChartLesson3.Models

    Partial Public Class GSP
        Public Property ID() As Integer
        Public Property Region() As String
        Public Property Year() As Integer?
        Public Property GSP1() As Double?
        Public Property SSMA_TimeStamp() As Byte()
    End Class
End Namespace
