//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartLesson3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSP
    {
        public int ID { get; set; }
        public string Region { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> GSP1 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
